<?php

use CRM_CivicrmAdminUi_ExtensionUtil as E;

    return [
      [
        'name' => 'SavedSearch_Personal_Campaign_Pages',
        'entity' => 'SavedSearch',
        'cleanup' => 'never',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Personal_Campaign_Pages',
            'label' => E::ts('Personal Campaign Pages'),
            'form_values' => NULL,
            'mapping_id' => NULL,
            'search_custom_id' => NULL,
            'api_entity' => 'PCP',
            'api_params' => [
              'version' => 4,
              'select' => [
                'id',
                'title',
                'is_active',
                'contact_id.display_name',
                'page_id',
                'page_type',
                'goal_amount',
              ],
              'orderBy' => [],
              'where' => [],
              'groupBy' => [],
              'join' => [],
              'having' => [],
            ],
            'expires_date' => NULL,
            'description' => NULL,
          ],
          'match' => [
            'name',
          ],
        ],
      ],
      [
        'name' => 'SavedSearch_Personal_Campaign_Pages_SearchDisplay_Personal_Campaign_Pages_Table_1',
        'entity' => 'SearchDisplay',
        'cleanup' => 'never',
        'update' => 'unmodified',
        'params' => [
          'version' => 4,
          'values' => [
            'name' => 'Personal_Campaign_Pages_Table_1',
            'label' => E::ts('Personal Campaign Pages Table 1'),
            'saved_search_id.name' => 'Personal_Campaign_Pages',
            'type' => 'table',
            'settings' => [
              'description' => NULL,
              'sort' => [],
              'limit' => 50,
              'pager' => [],
              'placeholder' => 5,
              'columns' => [
                [
                  'type' => 'field',
                  'key' => 'title',
                  'dataType' => 'String',
                  'label' => E::ts('Page Title'),
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'contact_id.display_name',
                  'dataType' => 'String',
                  'label' => E::ts('Supporter'),
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'is_active',
                  'dataType' => 'Boolean',
                  'label' => E::ts('Enabled'),
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'page_id',
                  'dataType' => 'Integer',
                  'label' => E::ts('Contribution Page'),
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'page_type',
                  'dataType' => 'String',
                  'label' => E::ts('PCP Page Type'),
                  'sortable' => TRUE,
                ],
                [
                  'type' => 'field',
                  'key' => 'goal_amount',
                  'dataType' => 'Money',
                  'label' => E::ts('Goal Amount'),
                  'sortable' => TRUE,
                ],
                [
                  'size' => 'btn-xs',
                  'links' => [
                    [
                      'path' => '',
                      'icon' => 'fa-save',
                      'text' => E::ts('Update'),
                      'style' => 'default',
                      'condition' => [],
                      'task' => 'update',
                      'entity' => 'PCP',
                      'action' => '',
                      'join' => '',
                      'target' => 'crm-popup',
                    ],
                    [
                      'task' => 'enable',
                      'entity' => 'PCP',
                      'join' => '',
                      'target' => 'crm-popup',
                      'icon' => 'fa-toggle-on',
                      'text' => E::ts('Enable'),
                      'style' => 'default',
                      'path' => '',
                      'action' => '',
                      'condition' => [
                        'is_active',
                        '=',
                        FALSE,
                      ],
                    ],
                    [
                      'task' => 'disable',
                      'entity' => 'PCP',
                      'join' => '',
                      'target' => 'crm-popup',
                      'icon' => 'fa-toggle-off',
                      'text' => E::ts('Disable'),
                      'style' => 'default',
                      'path' => '',
                      'action' => '',
                      'condition' => [
                        'is_active',
                        '=',
                        TRUE,
                      ],
                    ],
                    [
                      'task' => 'delete',
                      'entity' => 'PCP',
                      'join' => '',
                      'target' => 'crm-popup',
                      'icon' => 'fa-trash',
                      'text' => E::ts('Delete'),
                      'style' => 'danger',
                      'path' => '',
                      'action' => '',
                      'condition' => [],
                    ],
                  ],
                  'type' => 'buttons',
                  'alignment' => 'text-right',
                ],
              ],
              'actions' => TRUE,
              'classes' => [
                'table',
                'table-striped',
              ],
            ],
            'acl_bypass' => FALSE,
          ],
          'match' => [
            'name',
            'saved_search_id',
          ],
        ],
      ],
    ];
